---
title: "Emissions"
author: "Wajid Umar"
date: "03/11/2021"
output: html_document
---
# Graph 1
# Data extracted from FAO STAT website
```{r}
library(ggplot2)
g1<-ggplot(n, aes(Year, Value, fill=Area))+geom_area(stat = "identity", position = "stack")+
  scale_fill_manual(values = c("#F5AE02",  "#CBD805","#FF1F24","#02AD03"))+theme_bw()+
  scale_x_continuous(breaks = c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019))+
  labs(title = "N2O emissiom from rice straw burning (2010-2019)", x="Years", y="N2O emission (kilotonnes)", fill="Countries")+
  theme(axis.title = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 14), 
        title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14))
```

# Graph 2
# Data from FAO STAT

```{r}
g2<-ggplot(c, aes(Year, Value, fill=Area))+geom_bar(stat = "identity", position = position_dodge2())+theme_bw()+
  scale_x_continuous(breaks = c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019))+
  labs(title = "CH4 emissiom from rice straw burning (2010-2019)", x="Years", y="CH4 emission (kilotonnes)", fill="Countries")+
  theme(axis.title = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 14), 
        title = element_text(size = 16, face = "bold"),
        legend.text = element_text(size = 14))+scale_fill_manual(values = c("#F5FF00",  "#FA9D1C","#FA0001","#9BC034"))
```

# Combining both graph into one and saving

```{r}
library(ggpubr)
g3<-ggarrange(g1, g2, nrow = 2)

g3+ggsave("riceburning.png", units = "in", width = 8, height =5)
```

# Next twittter post
# Plot 1
```{r}
a1<-ggplot(g, aes(Year, Value, fill=Area))+geom_area()+
  scale_fill_manual(values = c("#02AD03", "#F5AE02", "#FF1F24", "#CBD805", "#FF5627"))+theme_bw()+
  labs(title = "CO2 emission intensity from cereals excluding rice (1961-2017)",x="", y="kg CO2eq/kg of product")+
  theme(axis.title = element_text(size = 14),
                                                               axis.text = element_text(size = 14), 
                                                               title = element_text(size = 16),
                                                               legend.text = element_text(size = 14))+
  scale_x_continuous(breaks = c(1961,1971,1981,1991,2001,2011,2017))
```

# plot 2

```{r}
a2<-ggplot(g, aes(Year, Value, fill=Area))+geom_jitter(aes(size=Value, col=Area))+
  scale_fill_manual(values = c("#02AD03", "#F5AE02", "#FF1F24", "#CBD805", "#FF5627"))+theme_bw()+
  labs(x="Years", y="kg CO2eq/kg of product", 
       caption = "DATA:https://www.fao.org/faostat/en/")+theme(axis.title = element_text(size = 14),
                                                               axis.text = element_text(size = 14), 
                                                               title = element_text(size = 16),
                                                               legend.text = element_text(size = 14))+
  scale_x_continuous(breaks = c(1961,1971,1981,1991,2001,2011,2017))
```

# Arranging graphs in one

```{r}
library(ggpubr)
a3<-ggarrange(a1, a2, nrow = 2)
a3
a3+ggsave("plot2.png", width = 8, height = 6, units = "in", dpi = 300)
```




